#!/usr/bin/perl -w

# CHANNEL ID MAPPER
# CONVERT CHANNEL NAMES INTO RYTEC IDs

## takealug.de
## github.com/sunsettrack4

my %REPLACE=(

### DE ###

 "Das Erste HD" 					=> "ARD.de" ,
 "ZDF HD" 							=> "ZDF.de" ,
 "hessen fernsehen" 				=> "HR.de" ,
 "RTL HD" 							=> "RTL.de" ,
 "RTL II HD"						=> "RTL2.de" ,
 "Super RTL HD" 					=> "SuperRTL.de" ,
 "RTL Crime HD" 					=> "RTLCrime.de" ,
 "RTL Nitro HD" 					=> "RTLNitro.de" ,
 "Kabel eins HD" 					=> "Kabel.de" ,
 "ProSieben HD" 					=> "Pro7.de" ,
 "ProSieben MAXX HD" 				=> "ProSiebenMaxx.de" ,
 "VOX HD" 							=> "Vox.de" ,
 "SAT1 HD" 							=> "Sat1.de" ,
 "DMAX HD" 							=> "DMax.de" ,
 "WELT HD" 							=> "WELT.de" ,
 "Sixx HD" 							=> "Sixx.de" ,
 "Disney Channel HD" 				=> "disneychannel.de" ,
 "Disney Junior" 					=> "DisneyJunior.de" ,
 "Disney Cinemagic HD" 				=> "DisneyCinemagic.de" ,
 "Kika HD" 							=> "Kika.de" ,
 "Nick HD" 							=> "Nickelodeon.de" ,
 "Discovery HD" 					=> "DiscoveryChannel.de" ,
 "Tele 5 HD" 						=> "Tele5.de" ,
 "Phoenix HD" 						=> "phoenix.de" ,
 "Fox HD" 							=> "Fox.de" ,
 "Sky Cinema HD" 					=> "SkyCinema.de" ,
 "Sky Cinema1"						=> "SkyCinemaPlus1.de" ,
 "Sky Cinema24" 					=> "SkyCinemaPlus24.de" ,
 "Sky Action HD" 					=> "SkyAction.de" ,
 "SKY Cinema Family HD"				=> "SkyFamily.de" ,
 "Sky Cinema Hits"					=> "SkyCinemaHits.de" ,
 "Sky Emotion" 						=> "SkyEmotion.de" ,
 "Sky Comedy" 						=> "SkyComedy.de" ,
 "Sky Atlantic HD" 					=> "SkyAtlanticHD.de" ,
 "SKY Arts" 						=> "SkyArts.de" ,
 "Sky Nostalgie" 					=> "SkyNostalgie.de" ,
 "Sky Krimi" 						=> "SkyKrimi.de" ,
 "MTV HD" 							=> "MTVGermany.de" ,
 "NatGeo HD" 						=> "NetGeo.de" ,
 "NatGeo Wild HD" 					=> "NatGeoWild.de" ,
 "Universal Channel HD" 			=> "Universal.de" ,
 "TNT Film HD" 						=> "TNTFilm.de" ,
 "TNT Serie HD" 					=> "TNTSerie.de" ,
 "TNT Comedy HD" 					=> "TNTComedy.de" ,
 "EEntertainment HD" 				=> "EEntertainment.de" ,
 "13th Street HD" 					=> "13thStreet.de" ,
 "SYFY HD" 							=> "SciFi.de" ,
 "ntv HD" 							=> "ntv.de" ,
 "HistoryHD"						=> "History.de" ,
 "TLC HD" 							=> "TLC.de" ,
 "Spiegel Geschichte" 				=> "SpiegelGeschichte.de" ,
 "Spiegel TV Wissen HD" 			=> "SpiegelTV.de" ,
 "WDR Köln HD" 						=> "WDR.de" ,
 "rbb Berlin HD" 					=> "rbbBerlin.de" ,
# "hr fernsehen HD" 				=> "HR.de" ,  ## DUPLIKAT ==> hessen fernsehen
 "NDR Hamburg" 						=> "ndr.de" ,
 "MDR Thüringen" 					=> "MDRThuringen.de" ,
 "Zee One" 							=> "ZeeOne.de" ,
 "Sport1 HD" 						=> "Sport1HD.de" ,
 "Sport1+ HD" 						=> "SPORT1plus.de" ,
 "Eurosport 1" 						=> "Eurosport1.de" ,
 "Eurosport 2" 						=> "Eurosport2.de" ,
 "EUROSPORT 2 HD XTRA" 				=> "Eurosport2Xtra.de" ,
 "Eurosport360 HD 1" 				=> "Eurosport360HD1.de" ,
 "Eurosport360 HD 2" 				=> "Eurosport360HD2.de" ,
 "Eurosport360 HD 3" 				=> "Eurosport360HD3.de" ,
 "Eurosport360 HD 4" 				=> "Eurosport360HD4.de" ,
 "Eurosport360 HD 5" 				=> "Eurosport360HD5.de" ,
 "Eurosport360 HD 6" 				=> "Eurosport360HD6.de" ,
 "Eurosport360 HD 7" 				=> "Eurosport360HD7.de" ,
 "Eurosport360 HD 8"				=> "Eurosport360HD8.de" ,
 "Eurosport360 HD 9" 				=> "Eurosport360HD9.de" ,
 "Sky Sports News HD" 				=> "SkySportNewsHD.de" ,
 "Sky Sport HD 1" 					=> "SkySport1.de" ,
 "Sky Sport HD 2" 					=> "SkySport2.de" ,
 "Sky Sport HD 3" 					=> "SkySport3.de" ,
 "Sky Sport HD 4" 					=> "SkySport4.de" ,
 "Sky Sport HD 5" 					=> "SkySport5.de" ,
 "Sky Sport 6" 						=> "SkySport6.de" ,
 "Sky Sport 7" 						=> "SkySport7.de" ,
 "Sky Sport 8" 						=> "SkySport8.de" ,
 "Sky Sport 9" 						=> "SkySport9.de" ,
 "Sky Sport 10" 					=> "SkySport10.de" ,
 "Sky Sport 11"		 				=> "SkySport11.de" ,
 "Sky Bundesliga HD 1" 				=> "SkyBundesliga1.de" ,
 "Sky Bundesliga HD 2" 				=> "SkyBundesliga2.de" ,
 "Sky Bundesliga HD 3" 				=> "SkyBundesliga3.de" ,
 "Sky Bundesliga HD 4" 				=> "SkyBundesliga4.de" ,
 "Sky Bundesliga 5"					=> "SkyBundesliga5.de" ,
 "Sky Bundesliga 6" 				=> "SkyBundesliga6.de" ,
 "Sky Bundesliga 7" 				=> "SkyBundesliga7.de" ,
 "Sky Bundesliga 8" 				=> "SkyBundesliga8.de" ,
 "Sky Bundesliga 9" 				=> "SkyBundesliga9.de" ,
 "Sky Bundesliga 10" 				=> "SkyBundesliga10.de" ,
 "DELUXE Music HD" 					=> "DeLuxeMusic.de" ,
 "SWR Fernsehen BW HD" 				=> "SWR.de" ,
 "RNFplus"		 					=> "RNF.de" ,
 "3sat HD" 							=> "3sat.de" ,
 "arte HD" 							=> "ARTE.de" ,
 "Servus TV DE HD" 					=> "ServusHD.de" ,
 "BR_Fernsehen_Sued_HD" 			=> "BR.de" ,
 "QVC HD" 							=> "QVC.de" ,
 "HSE24 HD" 						=> "HSE24.de" ,
 "sonnenklartv" 					=> "SonnenKlar.de" ,
 "123tv" 							=> "123.tv.de" ,
 "Juwelo TV HD" 					=> "JuweloTV.de" ,
 "QVC Plus HD" 						=> "QVCPlus.de" ,
 "HSE24 Extra HD"					=> "HSE24Extra.de" ,
 "QVC Beauty" 						=> "QVCBeauty.de" ,
 "Bibel TV HD" 						=> "BibelTV.de" ,
 "Planet HD" 						=> "PLANET.de" ,
 "Animal Planet HD" 				=> "AnimalPlanet.de" ,
 "RTL Living HD" 					=> "RTLLiving.de" ,
 "AE HD" 							=> "AandE.de" ,
 "Bon Gusto HD" 					=> "BonGusto.de" ,
# "Viva HD" 						=> "ComedyCentral/VIVA.de" , ## DUPLIKAT ==> Comedy Central
 "MTV Live HD" 						=> "MTVLiveHD.eu" ,
 "Classica HD" 						=> "Classica.eu" ,
 "ZDF neo HD" 						=> "ZDFneo.de" ,
 "ZDF Info HD" 						=> "ZDFinfo.de" ,
 "Sat1 Gold HD" 					=> "Sat1Gold.de" ,
 "ONE HD" 							=> "One.de" ,
 "Anixe HD"							=> "AnixeHD.de" ,
 "kabeleinsclassics HD" 			=> "KabelEinsClassic.de" ,
 "Kinowelt HD" 						=> "Kinowelt.de" ,
 "AXN HD" 							=> "AXN.de" ,
 "ProSieben Fun HD" 				=> "ProSiebenFun.de" ,
 "Romance TV HD" 					=> "Romance.de" ,
 "Auto Motor und Sport TV HD" 		=> "AutoMotorSport.de" ,
 "sportdigital HD" 					=> "sportdigital.de" ,
 "MOTORVISION TV HD" 				=> "MotorVision.de" ,
 "BBC HD" 							=> "BBCWorldNews.nws" ,
 "CNN Int HD" 						=> "CNN.nws" ,
 "Heimatkanal" 						=> "Heimatkanal.de" ,
 "BeateUhsetv" 						=> "BeateUhse.de" ,
 "Welt der Wunder" 					=> "WeltDerWunder.de" ,
 "N24 Doku" 						=> "N24Doku.de" ,
 "kabel eins Doku HD"				=> "KabelEinsDoku.de" ,
 "tagesschau24 HD" 					=> "tagesschau24.de" ,
 "ARD Alpha HD" 					=> "ARD-alpha.de" ,
 "RTLplus" 							=> "RTLPlus.de" ,
 "SR Fernsehen HD" 					=> "SRFernsehen.de" ,
 "Disney XD"						=> "DisneyXD.de" ,
 "Boomerang" 						=> "Boomerang.de" ,
 "Cartoon Network HD" 				=> "CartoonNetwork.de" ,
 "Junior" 							=> "Junior.de" ,
 "Jukebox" 							=> "Jukebox.de" ,
 "eoTV" 							=> "eoTV.de" ,
 "eSports1" 						=> "Sport1US.de" ,
 "MDR Sachsen HD" 					=> "MDRSachsen.de" ,
 "MTV Dance" 						=> "MTVDance.eu" ,
 "MTV Brand Neu" 					=> "MTVBrandNew.nl" ,
 "MTV Rocks" 						=> "MTVRocks.eu" ,
 "MTV Hits" 						=> "MTVHits.eu" ,
 "Nick Jr HD" 						=> "NickJr.de" ,
 "Radio Bremen TV" 					=> "RadioBremen.de" ,
 "RCKTV" 							=> "RCKTV.de" ,
 "Sat1 Emotions" 					=> "Sat1Comedy.de" ,
 "Silverline Movie Channel"			=> "Silverline.de" ,
 "Sky Sport Bundesliga UHD" 		=> "SkyBundesligaUHD.de" ,
 "Sky Sport UHD" 					=> "SkySportUHD.de" ,
 "Sony TV" 							=> "SonyEntertainmentTV.de" ,
 "TOGGO plus" 						=> "TOGGOplus.de" ,
 "Xite" 							=> "XITE.de" ,
 "RiC" 								=> "RiC.de" ,
 "Comedy Central" 					=> "ComedyCentral/VIVA.de" ,
 "TV5MONDE Europe" 					=> "TV5MondeEurope.fr" ,
 "Health TV" 						=> "HealthTV.de" ,
 "travelxp 4K"						=> "TravelXP.eu" ,
 
### AT ###
 
 "Sky Sport Austria HD" 			=> "SkySportAustria.de" ,
 "ORF eins" 						=> "ORF1.at" ,
 "ORF 2 Wien" 						=> "ORF2.at" ,
 "ORF III" 							=> "ORF3.at" ,
 "ORF Sport HD" 					=> "ORFSport.at" ,
 "ATV" 								=> "ATV.de" ,
 "ATV II HD" 						=> "ATV2.at" ,
 "PULS 4 HD" 						=> "Puls4.at" ,
 "W24 HD"							=> "W24.at" ,
 "R9 HD" 							=> "R9.at" ,
 "OKTO" 							=> "OKTO.at" ,
 "UPC Infokanal" 					=> "UPCinfo.at" ,
 "oe24TV" 							=> "oe24.at" ,
 "Tirol TV" 						=> "TirolTV.at" ,
 "KT 1" 							=> "KT1.at" ,
 "Ländle TV" 						=> "LandleTV.at" ,
 "Schau TV" 						=> "SchauTV.at" ,
 "Servus TV AT HD" 					=> "ServusTV.at" ,
 "gotv" 							=> "go.tv" ,
 
### CH ###

 "Bloomberg Europe TV" 				=> "Bloomberg.nws" ,
 "SRF 1 HD" 						=> "SRF1.ch" ,
 "SRF zwei HD" 						=> "SRF2.ch" ,
 "SRF info HD" 						=> "SRFinfo.ch" ,
 "3 HD" 							=> "3plus.ch" ,
 "TV24 HD" 							=> "TV24.ch" ,
 "S1 HD" 							=> "S1.ch" ,
 "Star TV HD" 						=> "StarTV.ch" ,
 "TeleZüri HD" 						=> "TeleZuri.ch" ,
 "MySports HD D" 					=> "MySports.ch" ,
 "Tele Bärn HD"						=> "TeleBaern.ch" ,
 "TeleBielingue HD" 				=> "TeleBielingue.ch" ,
 "Telebasel HD" 					=> "TeleBasel.ch" ,
 "Tele M1 HD" 						=> "TeleM1.ch" ,
 "Tele 1 HD" 						=> "Tele1.ch" ,
 "Tele Top HD" 						=> "TeleTop.ch" ,
 "TVO HD" 							=> "TVO.ch" ,
 "TV Südostschweiz HD" 				=> "TSO.ch" ,
 "TV25 HD" 							=> "TV25.ch" ,
 "Comedy HDVIVA HD" 				=> "ComedyCentral/VIVA.ch" ,
# "Servus TV CH HD" 				=> "ServusHD.de" , ## DUPLIKAT ==> Servus TV DE HD
 "euronews D" 						=> "EuronewsDE.nws" ,
 "VH1 Classic" 						=> "VH1Classic.eu" ,
 ) ;

my $PRE  = 'channel="' ;
my $POST = '">' ;

my $PREID  = 'channel id="' ;
my $POSTID = '">' ;

sub myfilter {
  my ($a) = @_;
  if ( exists $REPLACE{$a} ) {     
      return $REPLACE{$a} ;
  }else {
      print STDERR "Warning: Unmanaged channel: '$a'\n" ;
      return $a ;
   }
}

while (<>) {
    my $line = $_ ;
        $line =~ s/($PRE)(.*)($POST)/"$1".myfilter("$2")."$3"/ge ;
        $line =~ s/($PREID)(.*)($POSTID)/"$1".myfilter("$2")."$3"/ge ;
    print $line ;
}
